checks:
  php:
    code_rating: true
    duplication: true
filter:
  paths:
    - src/*
build:
  environment:
    php:
      version: 5.6
  tests:
    override:
      -
        command: 'composer test'
        coverage:
          file: 'build/logs/clover.xml'
          format: 'clover'
tools:
    php_sim: true
    php_mess_detector: true
    php_pdepend: true
    php_analyzer: true
    php_cpd: true
    php_mess_detector:
      enabled: true
      config:
        ruleset: ./phpmd.xml
    php_code_sniffer:
        enabled: true
        config:
          ruleset: ./phpcs.xml
