sudo: false
language: php
cache:
  directories:
    - $HOME/.composer/cache
    - vendor
before_install:
  - composer self-update
  - composer install
script:
 - composer test
matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7
    - php: hhvm
  allow_failures:
    - php: hhvm
